#pragma once

#include "CoreMinimal.h"

struct FRenamePlan;

/**
 * Safe C++ Rename Executor
 * - Backup before writing
 * - Atomic write (temp file -> move replace)
 * - Replacement hit count validation (optional strict)
 */
class FSafeCppRenameExecutor
{
public:
	/**
	 * Execute rename plan.
	 * @param Plan        Plan generated by PlanBuilder
	 * @param bDryRun     If true, do not write/rename anything, only report
	 * @param bStrict     If true, any 0-hit op will fail (recommended for v1)
	 * @param OutReport   Human-readable report (English)
	 * @return true if success
	 */
	static bool ExecutePlan(const FRenamePlan& Plan, bool bDryRun, bool bStrict, FString& OutReport);

private:
	// 中文注释：创建一个时间戳备份目录，如 Saved/SafeCppRename/Backup/2026-03-03_15-40-12/
	static bool CreateBackupDir(FString& OutBackupDirAbs, FString& OutError);

	// 中文注释：把计划里涉及的源文件备份到备份目录（保持文件名）
	static bool BackupFiles(const FRenamePlan& Plan, const FString& BackupDirAbs, FString& OutError);

	// 中文注释：原子写入：写到临时文件，然后 move 覆盖目标文件
	static bool AtomicWriteTextFile(const FString& TargetAbsPath, const FString& NewText, FString& OutError);

	// 中文注释：加载文本文件
	static bool LoadTextFile(const FString& AbsPath, FString& OutText, FString& OutError);

	// 中文注释：执行一个文件的替换操作，输出每个 Op 命中次数
	static bool ApplyReplacements(
		const FString& AbsPath,
		const TArray<struct FRenameTextReplaceOp>& Ops,
		bool bStrict,
		bool bDryRun,
		TArray<int32>& OutHitCounts,
		FString& OutError
	);

	// 中文注释：重命名文件（Move）
	static bool RenameFile(const FString& FromAbsPath, const FString& ToAbsPath, FString& OutError);

	// 中文注释：生成临时文件名
	static FString MakeTempPath(const FString& TargetAbsPath);
};